# Generated by Django 3.2.4 on 2021-07-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagramclone', '0004_alter_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
