# Generated by Django 3.2.4 on 2021-07-20 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagramclone', '0009_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-pk']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Post',
            new_name='post',
        ),
    ]
