# Generated by Django 3.2.4 on 2021-07-20 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagramclone', '0010_auto_20210720_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
