# Generated by Django 3.2.4 on 2021-07-23 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagramclone', '0012_auto_20210723_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='Post',
            new_name='post',
        ),
    ]
