# Generated by Django 3.2.4 on 2021-07-23 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagramclone', '0014_auto_20210723_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
